# Generated by Django 4.0.5 on 2022-07-07 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Type course name', max_length=200, unique=True, verbose_name='Course name')),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='courses/%Y/%m/%d')),
                ('date', models.DateTimeField(auto_now=True)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
