# Generated by Django 4.0.5 on 2022-07-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='name',
            field=models.CharField(help_text='Type course name', max_length=200, unique=True),
        ),
    ]
