# Generated by Django 4.0.5 on 2022-07-11 19:50

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_teachers_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
